<a href="https://colab.research.google.com/github/kevinshaji97/study/blob/feature-add/malware_cuckoo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
from sklearn.model_selection import train_test_split

In [0]:
data = pd.read_csv("/content/drive/My Drive/Malware Dataset/Malware dataset.csv")

In [133]:
len(data)

100000

In [0]:
data = data.dropna(how = 'all')

In [135]:
len(data)

100000

In [0]:
data.drop(data[data['classification'] =="benign" ].index, inplace = True)

In [137]:
len(data)

50000

In [0]:
data = data[:400]

In [139]:
len(data)

400

In [0]:
data.loc[0:100,"classification"] = "0"

In [0]:
data.loc[101:200,"classification"] = "1"

In [0]:
data.loc[201:300,"classification"] = "2"

In [0]:
data.loc[300:401,"classification"] = "3"

In [144]:
data

                                                  hash  ...  signal_nvcsw
0    42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
1    42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
2    42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
3    42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
4    42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
..                                                 ...  ...           ...
395  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
396  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
397  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
398  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
399  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0

[400 rows x 35 columns]

In [0]:
data = data.sample(frac=1).reset_index(drop=True)

In [0]:
from sklearn.model_selection import train_test_split

In [147]:
data

                                                  hash  ...  signal_nvcsw
0    42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
1    42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
2    42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
3    42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
4    42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
..                                                 ...  ...           ...
395  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
396  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
397  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
398  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0
399  42fb5e2ec009a05ff5143227297074f1e9c6c3ebb9c914...  ...             0

[400 rows x 35 columns]

In [0]:
label = data['classification']

In [149]:
label

0      0
1      0
2      1
3      2
4      2
      ..
395    3
396    3
397    2
398    3
399    2
Name: classification, Length: 400, dtype: object

In [0]:
data=data.drop(columns=['classification','hash'])

In [151]:
data

     millisecond  state  usage_counter  ...  gtime  cgtime  signal_nvcsw
0             68      0              0  ...      0       0             0
1             94      0              0  ...      0       0             0
2            142      0              0  ...      0       0             0
3            236      0              0  ...      0       0             0
4            212      0              0  ...      0       0             0
..           ...    ...            ...  ...    ...     ...           ...
395          364      0              0  ...      0       0             0
396          379   4096              0  ...      0       0             0
397          276      0              0  ...      0       0             0
398          369   4096              0  ...      0       0             0
399          295      0              0  ...      0       0             0

[400 rows x 33 columns]

In [0]:
x_train,x_test,y_train,y_test=train_test_split(data,label,test_size=0.3, random_state=42)

In [0]:
from sklearn.naive_bayes import GaussianNB

In [0]:
model = GaussianNB()

In [155]:
model.fit(x_train,y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [0]:
predicted= model.score(x_test,y_test)

In [157]:
predicted

0.6583333333333333

In [0]:
from sklearn.metrics import f1_score

In [0]:
# predict
y_pred = model.predict(x_test)

# f1 score
score = f1_score(y_pred, y_test, average='macro')

In [164]:
print(score)

0.6545806702184881